sprint 9 hw
krauklis-aa/java-filmorate pull request #5
Opened 2024-02-11 14:54 UTC by krauklis-aa

feature: добавлены модели Film, User, добавлены контроллеры и тесты валидации

2024-02-13 19:56 UTC, vlolad requested changes
Привет!

В целом все хорошо, пару минорных комментариев на улучшение. Есть лишняя зависимость в тестах, там подробно прокомментировал

В целом - супер! И Билдер в тестах использовала, это очень хорошо)

2024-02-13 19:56 UTC, vlolad commented on pom.xml
> +            <artifactId>spring-boot-starter-webflux</artifactId>
Долго искал, где же тут webflux. Нашел в тестах)

Оставил комментарий. Эта зависимость пока в проекте не нужна)

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(++id);
Можно добавить отдельный метод, который будет генерировать и возвращать актуальный ID. Так не придется прописывать инкременты каждый раз

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
Валидацию, кстати, можно вынести в аннотации к моделям с помощью spring-boot-starter-validation

Вот пример: https://struchkov.dev/blog/ru/spring-boot-validation/

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException(String.format("Фильм с id %d не найден", filmId));
Можно ещё ошибку NotFoundException кастомную сделать, будет неплохо)

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        String login = user.getLogin();
В таких случаях можно ещё в конце прописать .trim(), чтобы убрать пробелы по краям строки

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Builder
Можно ещё добавить аннотации из ломбока для создания конструкторов

2024-02-13 19:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Builder
Аналогично, можно добавить аннотации из ломбока для создания конструкторов

2024-02-13 19:56 UTC, vlolad commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> -	@Test
Тест на запуск контекста можно оставить, чтобы проверить запуск приложения

2024-02-13 19:56 UTC, vlolad commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +class FilmControllerTests {
И сразу успокою - потом будет отдельный спринт про интеграционные тесты, там вас научат, как запускать контекст приложения и проверять работу запросов целиком

2024-02-15 19:18 UTC, krauklis-aa commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
В ТЗ это отмечено как дополнительное задание. Сейчас у меня нет времени на него(

2024-02-16 14:56 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
Да, это на улучшение (но это оч удобно!)

2024-02-16 16:55 UTC, vlolad approved these changes
Огонь, все хорошо)

2024-02-23 21:12 UTC, merged