Add friends likes
krauklis-aa/java-filmorate pull request #6
Opened 2024-02-24 17:07 UTC by krauklis-aa

2024-02-25 22:49 UTC, vlolad requested changes
Привет!

В целом хорошо, есть небольшие недоработки по логированию и задвоением лайков, но в остальном все хорошо

Жду правок!

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/annotation/IsAfterMinReleaseDate.java
> +public @interface IsAfterMinReleaseDate {
Отлично!

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleNotFoundError(final NotFoundException e) {
Претензия к неймингу - Error это не Exception!!!

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Логгер есть, но логирования нет. Надо добавить на уроне info или debug - потом будет проще разбираться с ошибками с развитием проекта)

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Positive
ВООТ
Гораздо удобнее аннотациями валидировать же)

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +public class ErrorResponse {
Справедливости ради, ErrorResponse нормальный нейминг, т.к. это нативно понятно, что ответ уходит с ошибкой)
Можно ещё добавить поле с HTTP-статусом

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NotFoundException("Неверный userId");
Можно добавить в класс UserStorage и добавить проверку, что пользователь существует (просто получением его из базы)

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> usersWhoLiked = new HashSet<>();
Это можно оставить как единственное поле для лайков. Т.е. мы сохраняем ID пользователей лайкнувших и рейтинг рассчитываем по размеру коллекции. Требование по одному лайку на пользователя в этом случае сохраняется

Поле likes тут уже и не нужно

2024-02-25 22:49 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        likes++;
Сейчас можно несколько раз лайкать одному пользователю, надо доработать

2024-02-28 08:24 UTC, krauklis-aa commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
У нас добавлен Logbook, он все логирует, этого недостаточно?

2024-02-29 09:06 UTC, vlolad approved these changes
Привет!

Всё отлично, двигаемся дальше)

2024-02-29 09:12 UTC, merged